fix: compile error TS2564
Properties have no initializer and is not definitely assigned in
constructor. Property initialization was moved from helpers to
constructor for now.